In [58]:
import warnings
warnings.filterwarnings('ignore')

In [59]:
import pandas as pd
import datetime as dt
df = pd.read_csv('all_bikez_curated.csv')
df

,Brand,Model,Year,Category,Displacement (ccm),Power (hp),Engine cylinder,Engine stroke,Gearbox,Fuel capacity (lts),Fuel system,Fuel control,Cooling system,Transmission type,Dry weight (kg),Wheelbase (mm),Seat height (mm)
0,acabion,da vinci 650-vi,2011,Prototype / concept model,NaN,804.0,Electric,Electric,NaN,NaN,NaN,NaN,Liquid,Chain,420.0,NaN,NaN
1,acabion,gtbo 55,2007,Sport,1300.0,541.0,In-line four,four-stroke,6-speed,NaN,Turbo. KKK Acabion Extended,NaN,Liquid,NaN,360.0,NaN,NaN
2,acabion,gtbo 600 daytona-vi,2011,Prototype / concept model,NaN,536.0,Electric,Electric,NaN,NaN,NaN,NaN,Liquid,NaN,420.0,NaN,NaN
3,acabion,gtbo 600 daytona-vi,2021,Prototype / concept model,NaN,536.0,Electric,Electric,NaN,NaN,NaN,NaN,Liquid,NaN,420.0,NaN,NaN
4,acabion,gtbo 70,2007,Prototype / concept model,1300.0,689.0,In-line four,four-stroke,6-speed,NaN,Turbo. KKK Acabion Extended,NaN,Liquid,NaN,300.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38538,azel,aries 50,2009,Scooter,50.0,3.0,Single cylinder,four-stroke,Automatic,NaN,Carburettor,NaN,Air,Belt,84.0,1310.0,NaN
38539,azel,aries 50,2010,Scooter,49.0,3.0,Single cylinder,four-stroke,Automatic,NaN,Carburettor,NaN,Air,Chain,92.0,1310.0,NaN
38540,azel,atila 125,2009,Enduro / offroad,125.0,9.0,Single cylinder,four-stroke,Automatic,NaN,Carburettor,NaN,Air,Belt,120.0,1360.0,NaN
38541,azel,atila 125,2010,Enduro / offroad,125.0,9.0,Single cylinder,four-stroke,NaN,NaN,Carburettor,NaN,Air,Chain,120.0,1360.0,NaN
38542,azel,blackrose 250,2009,Custom / cruiser,248.0,18.0,V2,four-stroke,NaN,NaN,Carburettor,NaN,Air,Chain,175.0,1600.0,NaN

In [60]:
df.describe()

,Displacement (ccm),Power (hp),Fuel capacity (lts),Dry weight (kg),Wheelbase (mm),Seat height (mm)
count,37514.000000,26162.000000,31747.000000,22534.000000,25530.000000,24225.000000
mean,552.327129,50.739787,13.284891,164.102858,1423.003486,789.289659
std,545.335993,52.067367,6.009697,85.052614,172.586414,105.437801
min,25.000000,0.300000,0.500000,15.100000,725.000000,39.000000
25%,125.000000,12.000000,8.200000,105.000000,1321.000000,744.000000
50%,397.000000,30.000000,13.500000,145.000000,1422.000000,790.000000
75%,805.000000,77.000000,17.500000,199.600000,1500.000000,830.000000
max,8277.000000,804.000000,64.340000,1000.000000,3327.000000,7501.000000

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38543 entries, 0 to 38542
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brand                38543 non-null  object
 1   Model                38515 non-null  object
 2   Year                 38543 non-null  object
 3   Category             38543 non-null  object
 4   Displacement (ccm)   37514 non-null  float64
 5   Power (hp)           26162 non-null  float64
 6   Engine cylinder      38527 non-null  object
 7   Engine stroke        38532 non-null  object
 8   Gearbox              32733 non-null  object
 9   Fuel capacity (lts)  31747 non-null  float64
 10  Fuel system          27893 non-null  object
 11  Fuel control         22032 non-null  object
 12  Cooling system       34322 non-null  object
 13  Transmission type    32912 non-null  object
 14  Dry weight (kg)      22534 non-null  float64
 15  Wheelbase (mm)       25530 non-null  float64
 16  Seat height (mm)     24225 non-null  float64
dtypes: float64(6), object(11)
memory usage: 5.0+ MB

In [62]:
df['Category'].unique()

array(['Prototype / concept model', 'Sport', 'Scooter', 'ATV', 'Allround',
       'Naked bike', 'Custom / cruiser', 'Cross / motocross',
       'Super motard', 'Minibike, sport', 'Minibike, cross', 'Classic',
       'Touring', 'Enduro / offroad', 'Trial', 'Unspecified category',
       'Sport touring', 'Speedway'], dtype=object)

In [63]:
df['Displacement (ccm)'].fillna(df['Displacement (ccm)'].median(), inplace=True)
df['Power (hp)'].fillna(df['Power (hp)'].median(), inplace=True)

In [64]:
df['Fuel capacity (lts)'].fillna(df['Fuel capacity (lts)'].median(), inplace=True)
df['Dry weight (kg)'].fillna(df['Dry weight (kg)'].median(), inplace=True)

In [65]:
df['Wheelbase (mm)'].fillna(df['Wheelbase (mm)'].median(), inplace=True)
df['Seat height (mm)'].fillna(df['Seat height (mm)'].median(), inplace=True)

In [66]:
duplicate_rows = df[df.duplicated()]
duplicate_rows

,Brand,Model,Year,Category,Displacement (ccm),Power (hp),Engine cylinder,Engine stroke,Gearbox,Fuel capacity (lts),Fuel system,Fuel control,Cooling system,Transmission type,Dry weight (kg),Wheelbase (mm),Seat height (mm)
31114,sym,nh x 125,2020,Naked bike,124.1,10.1,Single cylinder,four-stroke,5-speed,11.0,Injection,NaN,Air,Chain,143.0,1400.0,790.0
38484,zÃ¼ndapp,518 ks 100,1969,Sport,100.0,30.0,Single cylinder,two-stroke,NaN,13.5,Carburettor. Bing,NaN,Air,Chain,95.0,1422.0,790.0
38485,zÃ¼ndapp,bella 151,1955,Scooter,147.0,7.3,Single cylinder,two-stroke,NaN,13.5,Carburettor,NaN,NaN,NaN,141.0,1422.0,790.0
38486,zÃ¼ndapp,bella 151,1956,Scooter,147.0,7.3,Single cylinder,two-stroke,NaN,13.5,Carburettor,NaN,NaN,NaN,141.0,1422.0,790.0
38487,zÃ¼ndapp,bella 175s,1961,Scooter,174.0,11.0,Single cylinder,two-stroke,4-speed,8.5,Carburettor. Bing 24mm,NaN,Air,NaN,146.0,1422.0,790.0
38488,yamaha,rd 350 (6-speed),1974,Classic,347.0,39.0,Twin,two-stroke,6-speed,16.0,Carburettor. Mikuni VM28 SC,Membrane,Air,Chain,155.0,1321.0,800.0
38489,yamaha,rd 350 (reduced effect),1985,Unspecified category,347.0,50.0,Twin,two-stroke,6-speed,20.0,NaN,Membrane & power valve,Liquid,Chain,145.0,1422.0,790.0
38490,yamaha,rd 350 (reduced effect),1986,Classic,347.0,50.0,Twin,two-stroke,6-speed,20.0,NaN,Membrane & power valve,Liquid,Chain,145.0,1422.0,790.0

In [67]:
duplicate_key = df[df.duplicated(subset=['Brand', 'Model', 'Year'], keep=False)]

In [68]:
#to drop duplicated values
df.drop_duplicates(subset=['Brand', 'Model', 'Year'], keep='first', inplace=True)